# Internal routing configuration to handle ESI
_home:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Home:index }
_evento:
    pattern:   /event/{slug}
    defaults:  { _controller: AcmeDemoBundle:Evento:mostrar } 